services:
  app:
    build: .
    container_name: go-wallet-app
    ports:
      - "8080:8080"
    env_file:
      - config.env
    volumes:
      - ./src:/app/src
      - /app/tmp
    restart: unless-stopped
  
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    env_file:
      - config.env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    